PROCESS
{
	$PATH = SPLIT-PATH -PARENT "C:\TEMP\*.*"
	$PATHEXIST = TEST-PATH -PATH $PATH
	IF ($PATHEXIST -EQ $FALSE)
	{NEW-ITEM -TYPE DIRECTORY -PATH $PATH}
	
	$REPORTDATE = GET-DATE -FORMAT yyyyMMdd
	
	$CSVREPORTFILE = $PATH + "\All AD Users - $REPORTDATE.csv"
	
	GET-ADUSER -PROPERTIES * -FILTER * | 
		SELECT-OBJECT @{LABEL = "FIRST NAME";EXPRESSION = {$_.GIVENNAME}},
		@{LABEL = "LAST NAME";EXPRESSION = {$_.SURNAME}},
		@{LABEL = "DISPLAY NAME";EXPRESSION = {$_.DISPLAYNAME}},
		@{LABEL = "LOGON NAME";EXPRESSION = {$_.SAMACCOUNTNAME}},
		@{LABEL = "FULL ADDRESS";EXPRESSION = {$_.STREETADDRESS}},
		@{LABEL = "CITY";EXPRESSION = {$_.CITY}},
		@{LABEL = "STATE";EXPRESSION = {$_.ST}},
		@{LABEL = "POST CODE";EXPRESSION = {$_.POSTALCODE}},
		@{LABEL = "JOB TITLE";EXPRESSION = {$_.TITLE}},
		@{LABEL = "COMPANY";EXPRESSION = {$_.COMPANY}},
		@{LABEL = "DEPARTMENT";EXPRESSION = {$_.DEPARTMENT}},
		@{LABEL = "OFFICE";EXPRESSION = {$_.OFFICENAME}},
		@{LABEL = "PHONE";EXPRESSION = {$_.TELEPHONENUMBER}},
		@{LABEL = "EMAIL";EXPRESSION = {$_.MAIL}} |	EXPORT-CSV -PATH $CSVREPORTFILE -NOTYPEINFORMATION     
}
