#==============================================================================================================================
# THIS SCRIPT WILL FIND ALL INSTALLED SOFTWARE ON A LOCAL COMPUTER
# AND SAVE THE INFORMATION IN A TEXT FILE. THE FILE WILL SAVE IN THE LOCATION "C:\TEMP"
#==============================================================================================================================

$COMPUTER = $ENV:COMPUTERNAME
$ARRAY = @()

FOREACH($TITLE IN $COMPUTER){
	$COMPUTERNAME = $TITLE.COMPUTERNAME
	$UNINSTALLKEY = "SOFTWARE\\MICROSOFT\\WINDOWS\\CURRENTVERSION\\UNINSTALL" 
	$REG = [MICROSOFT.WIN32.REGISTRYKEY]::OPENREMOTEBASEKEY('LOCALMACHINE',$COMPUTERNAME) 
	$REGKEY = $REG.OPENSUBKEY($UNINSTALLKEY) 
	$SUBKEYS = $REGKEY.GETSUBKEYNAMES() 
	
	FOREACH($KEY IN $SUBKEYS){
		$THISKEY=$UNINSTALLKEY+"\\"+$KEY 
		$THISSUBKEY=$REG.OPENSUBKEY($THISKEY) 
		$OBJ = NEW-OBJECT PSOBJECT
		$OBJ | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "COMPUTERNAME" -VALUE $COMPUTERNAME
		$OBJ | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "DISPLAYNAME" -VALUE $($THISSUBKEY.GETVALUE("DISPLAYNAME"))
		$OBJ | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "DISPLAYVERSION" -VALUE $($THISSUBKEY.GETVALUE("DISPLAYVERSION"))
		$OBJ | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "INSTALLLOCATION" -VALUE $($THISSUBKEY.GETVALUE("INSTALLLOCATION"))
		$OBJ | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "PUBLISHER" -VALUE $($THISSUBKEY.GETVALUE("PUBLISHER"))
		$ARRAY += $OBJ
	} 
}

$ARRAY | WHERE-OBJECT { $_.DISPLAYNAME } | SELECT DISPLAYNAME, DISPLAYVERSION, PUBLISHER | Format-lIST `
| FORMAT-WIDE -AutoSize | OUT-FILE -FILEPATH "C:\TEMP\INSTALLED_SOFTWARE.TXT"
