$ARRAY = @()

FOREACH ($COMPUTER IN $COMPUTERNAME = (GET-CONTENT C:\Filepath\ServerList.txt))
{
	IF(TEST-CONNECTION -COMPUTERNAME $COMPUTER -COUNT 1 -EA 0)
	{
		TRY
		{
			$NETWORKS = GET-WMIOBJECT WIN32_NETWORKADAPTERCONFIGURATION -COMPUTERNAME $COMPUTER -EA STOP | ? {$_.IPENABLED}
		}
			CATCH
			{
				WRITE-WARNING "ERROR OCCURRED WHILE QUERYING $COMPUTER."
				CONTINUE
			}
		FOREACH ($NETWORK IN $NETWORKS)
		{
			$IPADDRESS  = $NETWORK.IPADDRESS[0]
			$SUBNETMASK  = $NETWORK.IPSUBNET[0]
			$DEFAULTGATEWAY = $NETWORK.DEFAULTIPGATEWAY
			$DNSSERVERS  = $NETWORK.DNSSERVERSEARCHORDER
			#================================================================================================================================
			# THIS IS USED TO CHECK WHETHER DHCP IS ENABLED OR NOT.
			#================================================================================================================================
			#	$ISDHCPENABLED = $FALSE
			#
			#		IF($NETWORK.DHCPENABLED)
			#		{
			#			$ISDHCPENABLED = $TRUE
			#		}
			#================================================================================================================================
			$MACADDRESS  = $NETWORK.MACADDRESS
			$OUTPUTOBJ  = NEW-OBJECT -TYPE PSOBJECT
			$OUTPUTOBJ | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME COMPUTERNAME -VALUE $COMPUTER.TOUPPER()
			$OUTPUTOBJ | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME IPADDRESS -VALUE $IPADDRESS
			$OUTPUTOBJ | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME SUBNETMASK -VALUE $SUBNETMASK
			$OUTPUTOBJ | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME GATEWAY -VALUE ($DEFAULTGATEWAY -JOIN ",")      
			# $OUTPUTOBJ | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME ISDHCPENABLED -VALUE $ISDHCPENABLED
			$OUTPUTOBJ | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME DNSSERVERS -VALUE ($DNSSERVERS -JOIN ",")           
			$OUTPUTOBJ | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME MACADDRESS -VALUE $MACADDRESS
			
			$ARRAY += $OUTPUTOBJ
		}
	}
}

$ARRAY | EXPORT-CSV -PATH C:\TEMP\SCCMServerList.csv -NOTYPEINFORMATION
