PARAM
(
	[PARAMETER(POSITION = 0,MANDATORY = $FALSE)]
	[VALIDATENOTNULLOREMPTY()]
	[ALIAS('CN')][STRING[]]$COMPUTERNAME = $ENV:COMPUTERNAME, # OR Get-Content C:\FilePath\ComputerList.txt
	[PARAMETER(POSITION = 1,MANDATORY = $FALSE)]
	[ALIAS('UN')][STRING[]]$ACCOUNTNAME,
	[PARAMETER(POSITION = 2,MANDATORY = $FALSE)]
	[ALIAS('CRED')][SYSTEM.MANAGEMENT.AUTOMATION.PSCREDENTIAL]$CREDENTIAL
)
	
$OBJ = @()

FOREACH($COMPUTER IN $COMPUTERNAME)
{
	IF($CREDENTIAL)
	{
		$ALLLOCALACCOUNTS = GET-WMIOBJECT -CLASS WIN32_USERACCOUNT -NAMESPACE "ROOT\CIMV2" `
		-FILTER "LOCALACCOUNT = '$TRUE'" -COMPUTERNAME $COMPUTER -CREDENTIAL $CREDENTIAL -ERRORACTION STOP
	}
	ELSE
	{
		$ALLLOCALACCOUNTS = GET-WMIOBJECT -CLASS WIN32_USERACCOUNT -NAMESPACE "ROOT\CIMV2" `
		-FILTER "LOCALACCOUNT = '$TRUE'" -COMPUTERNAME $COMPUTER -ERRORACTION STOP
	}
	
	FOREACH($LOCALACCOUNT IN $ALLLOCALACCOUNTS)
	{
		$OBJECT = NEW-OBJECT -TYPENAME PSOBJECT
		
		$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "NAME" -VALUE $LOCALACCOUNT.NAME
		$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "FULL NAME" -VALUE $LOCALACCOUNT.FULLNAME
		$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "CAPTION" -VALUE $LOCALACCOUNT.CAPTION
      	$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "DISABLED" -VALUE $LOCALACCOUNT.DISABLED
      	$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "STATUS" -VALUE $LOCALACCOUNT.STATUS
      	$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "LOCKOUT" -VALUE $LOCALACCOUNT.LOCKOUT
		$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "PASSWORD CHANGEABLE" -VALUE $LOCALACCOUNT.PASSWORDCHANGEABLE
		$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "PASSWORD EXPIRES" -VALUE $LOCALACCOUNT.PASSWORDEXPIRES
		$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "PASSWORD REQUIRED" -VALUE $LOCALACCOUNT.PASSWORDREQUIRED
		$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "SID" -VALUE $LOCALACCOUNT.SID
		$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "SID TYPE" -VALUE $LOCALACCOUNT.SIDTYPE
		$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "ACCOUNT TYPE" -VALUE $LOCALACCOUNT.ACCOUNTTYPE
		$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "DOMAIN" -VALUE $LOCALACCOUNT.DOMAIN
		$OBJECT | ADD-MEMBER -MEMBERTYPE NOTEPROPERTY -NAME "DESCRIPTION" -VALUE $LOCALACCOUNT.DESCRIPTION
		
		$OBJ += $OBJECT
	}
	
	IF($ACCOUNTNAME)
	{
		FOREACH($ACCOUNT IN $ACCOUNTNAME)
		{
			$OBJ | WHERE-OBJECT{$_.NAME -LIKE "$ACCOUNT"}
		}
	}
	ELSE
	{
		$OBJ
	}
}
